branch: 'main' # default is master
threshold_score: 2 # default is 0
minimum_score: 95 # default is 0
paths:
  - "app/builders"
  - "app/controllers"
  - "app/decorators"
  - "app/helpers"
  - "app/jobs"
  - "app/mailers"
  - "app/models"
  - "app/policies"
  - "app/services"
