default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>.sqlite3

queue: &queue
  <<: *default
  database: storage/<%= Rails.env %>-queue.sqlite3
  migrations_paths: db/queue_migrate

development:
  primary: *primary
  queue: *queue

test:
  primary: *primary
  queue: *queue

staging:
  primary: *primary
  queue: *queue

production:
  primary: *primary
  queue: *queue
