default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>.sqlite3

# Because Solid Queue is constantly polling the database and making frequent updates,
# it is recommended to use a separate database for the queue when using Solid Queue with SQLite.
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: storage/<%= Rails.env %>-queue.sqlite3

development:
  primary: *primary
  queue: *queue

test:
  primary: *primary
  queue: *queue

staging:
  primary: *primary
  queue: *queue

production:
  primary: *primary
  queue: *queue
