service: rails-world
image: ibramsterdam/rails-world

# Use a persistent storage volume for sqlite.
volumes:
  - storage:/rails/storage

# Credentials for your image host, we recommend Docker Hub.
registry:
  username: ibramsterdam
  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

aliases:
  console: app exec -i --reuse "bin/rails console"

# Force specification of staging or production deployment
require_destination: true

