# Specify the list of directories to be included into the final
# app.wasm file.
pack_directories:
  - app
  - lib
  - config
  - db
  - public

# Specify the list of gems to skip during the base module compiliation.
# Usually, you want to specify the gems with native extensions that are
# not currently Wasm-compatible.
exclude_gems:
  - bigdecimal
  - nio4r
  - io-console
  - psych
  - date
output_dir: "pwa"